# Generated by Django 3.2.9 on 2021-12-03 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9 \\-\\_]+$')])),
                ('description', models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\_\\-\\(\\)\\.\\,\\;\\&\\:\\=\\è\\\'\\"\\! ]{1,100}$')])),
                ('category', models.CharField(max_length=25, verbose_name=[('AS_NEW', 'As New'), ('GOOD_CONDITION', 'Good Condition'), ('ACCEPTABLE_CONDITION', 'Acceptable Condition')])),
                ('brand', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
