# Generated by Django 3.2.9 on 2021-12-03 17:21

import FleaMarketItem.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleaMarketItem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default=1, max_length=25, verbose_name=[('AS_NEW', 'As New'), ('GOOD_CONDITION', 'Good Condition'), ('ACCEPTABLE_CONDITION', 'Acceptable Condition')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1, validators=[FleaMarketItem.validators.validate_price]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\_\\-\\(\\)\\.\\,\\;\\&\\:\\=\\è\\\'\\"\\! ]{1,25}$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\_\\-\\(\\)\\.\\,\\;\\&\\:\\=\\è\\\'\\"\\! ]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=450, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\_\\-\\(\\)\\.\\,\\;\\&\\:\\=\\è\\\'\\"\\! ]{1,100}$')]),
        ),
    ]
