# Generated by Django 3.2.9 on 2021-12-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleaMarketItem', '0002_auto_20211203_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(max_length=25, verbose_name=[('AN', 'AS_NEW'), ('GC', 'GOOD_CONDITION'), ('AC', 'ACCEPTABLE_CONDITION')]),
        ),
    ]
