# Generated by Django 3.2.9 on 2021-12-09 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleaMarketItem', '0003_alter_item_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z\\_\\-\\(\\)]+$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z\\_\\-\\(\\) ]+$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.IntegerField(choices=[(0, 'AS_NEW'), (1, 'GOOD_CONDITION'), (2, 'ACCEPTABLE_CONDITION')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\(\\)\\!\\,\\è\\:\\;\\\'\\"\\. ]+$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')]),
        ),
    ]
