# Generated by Django 3.2.7 on 2021-12-13 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FleaMarketItem', '0004_auto_20211209_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\(\\)\\!\\,\\è\\:\\;\\\'\\"\\. ]*$')]),
        ),
    ]
